theme: jekyll-theme-minimal
title: Excelsiorhaus Mietergemeinschaft
description: Excelsiorhaus Tenant Association
repository: username/repository-name

collections:
  past_meetings:
    output: true
    sort_by: date
